### ISSUE TITLE
Change docker image registry from cloudstateio to bintray

### ISSUE THREAD

**Issue by tringuyen-yw** [cloudstateio/samples-ui-chat#4]
Current chat-ui docker image location: cloudstateio/samples-js-chat-ui:latest

TODO:

- Rename to **chat-ui**:latest
- Push to lightbend-docker-registry.bintray.io/cloudstate-samples/chat-ui:latest

**Comment by vkorenev** [comment]
Commit 80fa25704ebf8b3d1da7595353315a686f3f718c was tagged as `v0.1.0` and the following images were built from it and pushed to [the Ligtbend Docker registry on Bintray](https://bintray.com/beta/#/lightbend/registry):
- `lightbend-docker-registry.bintray.io/cloudstate-samples/chat-ui:0.1.0`
- `lightbend-docker-registry.bintray.io/cloudstate-samples/chat-ui:latest`
